### ISSUE TITLE
Fourier transform for initial Div B = 0, Div E = rho

### ISSUE THREAD

**Issue by DenSto** [DenSto/APC_524_Project#25]
For testing, we should solve the poisson equation using a Fourier transform. That will at least ensure that the initial conditions make sense.

**Comment by aglasser17** [comment]
I think the issues we are having with the Jacobi method are unrelated to the method and more related to two issues, which would be just as problematic for a Fourier Poisson solver:

(1) How exactly we handle the ghost cells.  I think we need to average them...but I want to think about it more.  Very open to suggestions...

(2) We must also ensure that total particle charge is zero if we implement periodic boundary conditions.  Otherwise, the Fredholm alternative says no solutions to Poisson's equation exist.

**Comment by aglasser17** [comment]
h = 1;  %h is length of each cell.

%r is a rho variable, deposited only at the physical vertices #2 - 4.
%Therefore r = 0 on the ghost cells, #1 and #5.

%Note that only cases for which sum(r) = 0 converge.
%r = [0 1 1 -3 0]; %X
 r = [0 1 -3 1 0]; %X
%r = [0 1 1 -2 0]; %Converges
%r = [0 1 2 -3 0]; %Converges
%r = [0 9 -9 0 0]; %Converges

pold = zeros(1,5);
pnew = pold;
for k = 1:100
    for j = 2:4
        pnew(j) = (pold(j-1)+pold(j+1)) / 2   -h^2*r(j) / 2; %Discretized Laplacian step: p^{n+1}_i = [p^n_{i-1}+p^n_{i+1}]/2 - h^2*r_i
    end

    pold = pnew;
    pold(1) = pnew(4);  %Send last physical vertex to start ghost vertex
    pold(5) = pnew(2);  %Send first physical vertex to end ghost vertex

    disp(pnew);
    pause(.1);
end

**Comment by aglasser17** [comment]
Above is a brief MATLAB script that demonstrates simply how Poisson should work...only the outermost vertices just need to be copied in...

Note that the product sign <asterisk> is converted to italics ....sorry about that.

**Comment by aglasser17** [comment]
Since Poisson is now converging quickly with the Jacobi method, I am retiring this issue.
